apiVersion: apps/v1
kind: Deployment
metadata:
  name: memtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memtest
  template:
    metadata:
      labels:
        app: memtest
    spec:
      containers:
      - name: memtest
        image: memtest:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: memtest
spec:
  selector:
    app: memtest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
